// Generated by gencpp from file anymal_rsl_recording/StartRecordingInternal.msg
// DO NOT EDIT!


#ifndef ANYMAL_RSL_RECORDING_MESSAGE_STARTRECORDINGINTERNAL_H
#define ANYMAL_RSL_RECORDING_MESSAGE_STARTRECORDINGINTERNAL_H

#include <ros/service_traits.h>


#include <anymal_rsl_recording/StartRecordingInternalRequest.h>
#include <anymal_rsl_recording/StartRecordingInternalResponse.h>


namespace anymal_rsl_recording
{

struct StartRecordingInternal
{

typedef StartRecordingInternalRequest Request;
typedef StartRecordingInternalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StartRecordingInternal
} // namespace anymal_rsl_recording


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::anymal_rsl_recording::StartRecordingInternal > {
  static const char* value()
  {
    return "31953adc5c144f572ee1dd85f7900ed7";
  }

  static const char* value(const ::anymal_rsl_recording::StartRecordingInternal&) { return value(); }
};

template<>
struct DataType< ::anymal_rsl_recording::StartRecordingInternal > {
  static const char* value()
  {
    return "anymal_rsl_recording/StartRecordingInternal";
  }

  static const char* value(const ::anymal_rsl_recording::StartRecordingInternal&) { return value(); }
};


// service_traits::MD5Sum< ::anymal_rsl_recording::StartRecordingInternalRequest> should match
// service_traits::MD5Sum< ::anymal_rsl_recording::StartRecordingInternal >
template<>
struct MD5Sum< ::anymal_rsl_recording::StartRecordingInternalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::anymal_rsl_recording::StartRecordingInternal >::value();
  }
  static const char* value(const ::anymal_rsl_recording::StartRecordingInternalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::anymal_rsl_recording::StartRecordingInternalRequest> should match
// service_traits::DataType< ::anymal_rsl_recording::StartRecordingInternal >
template<>
struct DataType< ::anymal_rsl_recording::StartRecordingInternalRequest>
{
  static const char* value()
  {
    return DataType< ::anymal_rsl_recording::StartRecordingInternal >::value();
  }
  static const char* value(const ::anymal_rsl_recording::StartRecordingInternalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::anymal_rsl_recording::StartRecordingInternalResponse> should match
// service_traits::MD5Sum< ::anymal_rsl_recording::StartRecordingInternal >
template<>
struct MD5Sum< ::anymal_rsl_recording::StartRecordingInternalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::anymal_rsl_recording::StartRecordingInternal >::value();
  }
  static const char* value(const ::anymal_rsl_recording::StartRecordingInternalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::anymal_rsl_recording::StartRecordingInternalResponse> should match
// service_traits::DataType< ::anymal_rsl_recording::StartRecordingInternal >
template<>
struct DataType< ::anymal_rsl_recording::StartRecordingInternalResponse>
{
  static const char* value()
  {
    return DataType< ::anymal_rsl_recording::StartRecordingInternal >::value();
  }
  static const char* value(const ::anymal_rsl_recording::StartRecordingInternalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ANYMAL_RSL_RECORDING_MESSAGE_STARTRECORDINGINTERNAL_H
