// Generated by gencpp from file anymal_rsl_recording/StartRecordingInternalResponse.msg
// DO NOT EDIT!


#ifndef ANYMAL_RSL_RECORDING_MESSAGE_STARTRECORDINGINTERNALRESPONSE_H
#define ANYMAL_RSL_RECORDING_MESSAGE_STARTRECORDINGINTERNALRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace anymal_rsl_recording
{
template <class ContainerAllocator>
struct StartRecordingInternalResponse_
{
  typedef StartRecordingInternalResponse_<ContainerAllocator> Type;

  StartRecordingInternalResponse_()
    : suc(false)
    , message()  {
    }
  StartRecordingInternalResponse_(const ContainerAllocator& _alloc)
    : suc(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _suc_type;
  _suc_type suc;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::anymal_rsl_recording::StartRecordingInternalResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::anymal_rsl_recording::StartRecordingInternalResponse_<ContainerAllocator> const> ConstPtr;

}; // struct StartRecordingInternalResponse_

typedef ::anymal_rsl_recording::StartRecordingInternalResponse_<std::allocator<void> > StartRecordingInternalResponse;

typedef boost::shared_ptr< ::anymal_rsl_recording::StartRecordingInternalResponse > StartRecordingInternalResponsePtr;
typedef boost::shared_ptr< ::anymal_rsl_recording::StartRecordingInternalResponse const> StartRecordingInternalResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::anymal_rsl_recording::StartRecordingInternalResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::anymal_rsl_recording::StartRecordingInternalResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::anymal_rsl_recording::StartRecordingInternalResponse_<ContainerAllocator1> & lhs, const ::anymal_rsl_recording::StartRecordingInternalResponse_<ContainerAllocator2> & rhs)
{
  return lhs.suc == rhs.suc &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::anymal_rsl_recording::StartRecordingInternalResponse_<ContainerAllocator1> & lhs, const ::anymal_rsl_recording::StartRecordingInternalResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace anymal_rsl_recording

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::anymal_rsl_recording::StartRecordingInternalResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::anymal_rsl_recording::StartRecordingInternalResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::anymal_rsl_recording::StartRecordingInternalResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::anymal_rsl_recording::StartRecordingInternalResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::anymal_rsl_recording::StartRecordingInternalResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::anymal_rsl_recording::StartRecordingInternalResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::anymal_rsl_recording::StartRecordingInternalResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b6126c73bcef51911f25484629552cec";
  }

  static const char* value(const ::anymal_rsl_recording::StartRecordingInternalResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb6126c73bcef5191ULL;
  static const uint64_t static_value2 = 0x1f25484629552cecULL;
};

template<class ContainerAllocator>
struct DataType< ::anymal_rsl_recording::StartRecordingInternalResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "anymal_rsl_recording/StartRecordingInternalResponse";
  }

  static const char* value(const ::anymal_rsl_recording::StartRecordingInternalResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::anymal_rsl_recording::StartRecordingInternalResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool suc\n"
"string message\n"
;
  }

  static const char* value(const ::anymal_rsl_recording::StartRecordingInternalResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::anymal_rsl_recording::StartRecordingInternalResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.suc);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StartRecordingInternalResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::anymal_rsl_recording::StartRecordingInternalResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::anymal_rsl_recording::StartRecordingInternalResponse_<ContainerAllocator>& v)
  {
    s << indent << "suc: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.suc);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ANYMAL_RSL_RECORDING_MESSAGE_STARTRECORDINGINTERNALRESPONSE_H
