// Generated by gencpp from file anymal_rsl_recording/StartRecordingResponse.msg
// DO NOT EDIT!


#ifndef ANYMAL_RSL_RECORDING_MESSAGE_STARTRECORDINGRESPONSE_H
#define ANYMAL_RSL_RECORDING_MESSAGE_STARTRECORDINGRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace anymal_rsl_recording
{
template <class ContainerAllocator>
struct StartRecordingResponse_
{
  typedef StartRecordingResponse_<ContainerAllocator> Type;

  StartRecordingResponse_()
    : timestamp()
    , suc(false)
    , message()  {
    }
  StartRecordingResponse_(const ContainerAllocator& _alloc)
    : timestamp(_alloc)
    , suc(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _timestamp_type;
  _timestamp_type timestamp;

   typedef uint8_t _suc_type;
  _suc_type suc;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::anymal_rsl_recording::StartRecordingResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::anymal_rsl_recording::StartRecordingResponse_<ContainerAllocator> const> ConstPtr;

}; // struct StartRecordingResponse_

typedef ::anymal_rsl_recording::StartRecordingResponse_<std::allocator<void> > StartRecordingResponse;

typedef boost::shared_ptr< ::anymal_rsl_recording::StartRecordingResponse > StartRecordingResponsePtr;
typedef boost::shared_ptr< ::anymal_rsl_recording::StartRecordingResponse const> StartRecordingResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::anymal_rsl_recording::StartRecordingResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::anymal_rsl_recording::StartRecordingResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::anymal_rsl_recording::StartRecordingResponse_<ContainerAllocator1> & lhs, const ::anymal_rsl_recording::StartRecordingResponse_<ContainerAllocator2> & rhs)
{
  return lhs.timestamp == rhs.timestamp &&
    lhs.suc == rhs.suc &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::anymal_rsl_recording::StartRecordingResponse_<ContainerAllocator1> & lhs, const ::anymal_rsl_recording::StartRecordingResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace anymal_rsl_recording

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::anymal_rsl_recording::StartRecordingResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::anymal_rsl_recording::StartRecordingResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::anymal_rsl_recording::StartRecordingResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::anymal_rsl_recording::StartRecordingResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::anymal_rsl_recording::StartRecordingResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::anymal_rsl_recording::StartRecordingResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::anymal_rsl_recording::StartRecordingResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b3c1649a8e42db27d21a60be319b4a96";
  }

  static const char* value(const ::anymal_rsl_recording::StartRecordingResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb3c1649a8e42db27ULL;
  static const uint64_t static_value2 = 0xd21a60be319b4a96ULL;
};

template<class ContainerAllocator>
struct DataType< ::anymal_rsl_recording::StartRecordingResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "anymal_rsl_recording/StartRecordingResponse";
  }

  static const char* value(const ::anymal_rsl_recording::StartRecordingResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::anymal_rsl_recording::StartRecordingResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string timestamp\n"
"bool suc\n"
"string message\n"
;
  }

  static const char* value(const ::anymal_rsl_recording::StartRecordingResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::anymal_rsl_recording::StartRecordingResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.suc);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StartRecordingResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::anymal_rsl_recording::StartRecordingResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::anymal_rsl_recording::StartRecordingResponse_<ContainerAllocator>& v)
  {
    s << indent << "timestamp: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.timestamp);
    s << indent << "suc: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.suc);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ANYMAL_RSL_RECORDING_MESSAGE_STARTRECORDINGRESPONSE_H
