// Generated by gencpp from file anymal_rsl_recording/StartRecordingRequest.msg
// DO NOT EDIT!


#ifndef ANYMAL_RSL_RECORDING_MESSAGE_STARTRECORDINGREQUEST_H
#define ANYMAL_RSL_RECORDING_MESSAGE_STARTRECORDINGREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace anymal_rsl_recording
{
template <class ContainerAllocator>
struct StartRecordingRequest_
{
  typedef StartRecordingRequest_<ContainerAllocator> Type;

  StartRecordingRequest_()
    : yaml_file()  {
    }
  StartRecordingRequest_(const ContainerAllocator& _alloc)
    : yaml_file(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _yaml_file_type;
  _yaml_file_type yaml_file;





  typedef boost::shared_ptr< ::anymal_rsl_recording::StartRecordingRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::anymal_rsl_recording::StartRecordingRequest_<ContainerAllocator> const> ConstPtr;

}; // struct StartRecordingRequest_

typedef ::anymal_rsl_recording::StartRecordingRequest_<std::allocator<void> > StartRecordingRequest;

typedef boost::shared_ptr< ::anymal_rsl_recording::StartRecordingRequest > StartRecordingRequestPtr;
typedef boost::shared_ptr< ::anymal_rsl_recording::StartRecordingRequest const> StartRecordingRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::anymal_rsl_recording::StartRecordingRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::anymal_rsl_recording::StartRecordingRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::anymal_rsl_recording::StartRecordingRequest_<ContainerAllocator1> & lhs, const ::anymal_rsl_recording::StartRecordingRequest_<ContainerAllocator2> & rhs)
{
  return lhs.yaml_file == rhs.yaml_file;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::anymal_rsl_recording::StartRecordingRequest_<ContainerAllocator1> & lhs, const ::anymal_rsl_recording::StartRecordingRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace anymal_rsl_recording

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::anymal_rsl_recording::StartRecordingRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::anymal_rsl_recording::StartRecordingRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::anymal_rsl_recording::StartRecordingRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::anymal_rsl_recording::StartRecordingRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::anymal_rsl_recording::StartRecordingRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::anymal_rsl_recording::StartRecordingRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::anymal_rsl_recording::StartRecordingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f39929436acc1b6fe810c855cd8cc9ef";
  }

  static const char* value(const ::anymal_rsl_recording::StartRecordingRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf39929436acc1b6fULL;
  static const uint64_t static_value2 = 0xe810c855cd8cc9efULL;
};

template<class ContainerAllocator>
struct DataType< ::anymal_rsl_recording::StartRecordingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "anymal_rsl_recording/StartRecordingRequest";
  }

  static const char* value(const ::anymal_rsl_recording::StartRecordingRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::anymal_rsl_recording::StartRecordingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string yaml_file\n"
;
  }

  static const char* value(const ::anymal_rsl_recording::StartRecordingRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::anymal_rsl_recording::StartRecordingRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.yaml_file);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StartRecordingRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::anymal_rsl_recording::StartRecordingRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::anymal_rsl_recording::StartRecordingRequest_<ContainerAllocator>& v)
  {
    s << indent << "yaml_file: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.yaml_file);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ANYMAL_RSL_RECORDING_MESSAGE_STARTRECORDINGREQUEST_H
