// Generated by gencpp from file anymal_rsl_recording/StartRecordingInternalRequest.msg
// DO NOT EDIT!


#ifndef ANYMAL_RSL_RECORDING_MESSAGE_STARTRECORDINGINTERNALREQUEST_H
#define ANYMAL_RSL_RECORDING_MESSAGE_STARTRECORDINGINTERNALREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace anymal_rsl_recording
{
template <class ContainerAllocator>
struct StartRecordingInternalRequest_
{
  typedef StartRecordingInternalRequest_<ContainerAllocator> Type;

  StartRecordingInternalRequest_()
    : topics()
    , timestamp()  {
    }
  StartRecordingInternalRequest_(const ContainerAllocator& _alloc)
    : topics(_alloc)
    , timestamp(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _topics_type;
  _topics_type topics;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _timestamp_type;
  _timestamp_type timestamp;





  typedef boost::shared_ptr< ::anymal_rsl_recording::StartRecordingInternalRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::anymal_rsl_recording::StartRecordingInternalRequest_<ContainerAllocator> const> ConstPtr;

}; // struct StartRecordingInternalRequest_

typedef ::anymal_rsl_recording::StartRecordingInternalRequest_<std::allocator<void> > StartRecordingInternalRequest;

typedef boost::shared_ptr< ::anymal_rsl_recording::StartRecordingInternalRequest > StartRecordingInternalRequestPtr;
typedef boost::shared_ptr< ::anymal_rsl_recording::StartRecordingInternalRequest const> StartRecordingInternalRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::anymal_rsl_recording::StartRecordingInternalRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::anymal_rsl_recording::StartRecordingInternalRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::anymal_rsl_recording::StartRecordingInternalRequest_<ContainerAllocator1> & lhs, const ::anymal_rsl_recording::StartRecordingInternalRequest_<ContainerAllocator2> & rhs)
{
  return lhs.topics == rhs.topics &&
    lhs.timestamp == rhs.timestamp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::anymal_rsl_recording::StartRecordingInternalRequest_<ContainerAllocator1> & lhs, const ::anymal_rsl_recording::StartRecordingInternalRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace anymal_rsl_recording

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::anymal_rsl_recording::StartRecordingInternalRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::anymal_rsl_recording::StartRecordingInternalRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::anymal_rsl_recording::StartRecordingInternalRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::anymal_rsl_recording::StartRecordingInternalRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::anymal_rsl_recording::StartRecordingInternalRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::anymal_rsl_recording::StartRecordingInternalRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::anymal_rsl_recording::StartRecordingInternalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6375c601750e77d58959cb8fac445f25";
  }

  static const char* value(const ::anymal_rsl_recording::StartRecordingInternalRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6375c601750e77d5ULL;
  static const uint64_t static_value2 = 0x8959cb8fac445f25ULL;
};

template<class ContainerAllocator>
struct DataType< ::anymal_rsl_recording::StartRecordingInternalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "anymal_rsl_recording/StartRecordingInternalRequest";
  }

  static const char* value(const ::anymal_rsl_recording::StartRecordingInternalRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::anymal_rsl_recording::StartRecordingInternalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string topics\n"
"string timestamp\n"
;
  }

  static const char* value(const ::anymal_rsl_recording::StartRecordingInternalRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::anymal_rsl_recording::StartRecordingInternalRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.topics);
      stream.next(m.timestamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StartRecordingInternalRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::anymal_rsl_recording::StartRecordingInternalRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::anymal_rsl_recording::StartRecordingInternalRequest_<ContainerAllocator>& v)
  {
    s << indent << "topics: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.topics);
    s << indent << "timestamp: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.timestamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ANYMAL_RSL_RECORDING_MESSAGE_STARTRECORDINGINTERNALREQUEST_H
