// Generated by gencpp from file anymal_rsl_recording/StopRecording.msg
// DO NOT EDIT!


#ifndef ANYMAL_RSL_RECORDING_MESSAGE_STOPRECORDING_H
#define ANYMAL_RSL_RECORDING_MESSAGE_STOPRECORDING_H

#include <ros/service_traits.h>


#include <anymal_rsl_recording/StopRecordingRequest.h>
#include <anymal_rsl_recording/StopRecordingResponse.h>


namespace anymal_rsl_recording
{

struct StopRecording
{

typedef StopRecordingRequest Request;
typedef StopRecordingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StopRecording
} // namespace anymal_rsl_recording


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::anymal_rsl_recording::StopRecording > {
  static const char* value()
  {
    return "32fb2cde53384a7b9732fe4867a515c5";
  }

  static const char* value(const ::anymal_rsl_recording::StopRecording&) { return value(); }
};

template<>
struct DataType< ::anymal_rsl_recording::StopRecording > {
  static const char* value()
  {
    return "anymal_rsl_recording/StopRecording";
  }

  static const char* value(const ::anymal_rsl_recording::StopRecording&) { return value(); }
};


// service_traits::MD5Sum< ::anymal_rsl_recording::StopRecordingRequest> should match
// service_traits::MD5Sum< ::anymal_rsl_recording::StopRecording >
template<>
struct MD5Sum< ::anymal_rsl_recording::StopRecordingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::anymal_rsl_recording::StopRecording >::value();
  }
  static const char* value(const ::anymal_rsl_recording::StopRecordingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::anymal_rsl_recording::StopRecordingRequest> should match
// service_traits::DataType< ::anymal_rsl_recording::StopRecording >
template<>
struct DataType< ::anymal_rsl_recording::StopRecordingRequest>
{
  static const char* value()
  {
    return DataType< ::anymal_rsl_recording::StopRecording >::value();
  }
  static const char* value(const ::anymal_rsl_recording::StopRecordingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::anymal_rsl_recording::StopRecordingResponse> should match
// service_traits::MD5Sum< ::anymal_rsl_recording::StopRecording >
template<>
struct MD5Sum< ::anymal_rsl_recording::StopRecordingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::anymal_rsl_recording::StopRecording >::value();
  }
  static const char* value(const ::anymal_rsl_recording::StopRecordingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::anymal_rsl_recording::StopRecordingResponse> should match
// service_traits::DataType< ::anymal_rsl_recording::StopRecording >
template<>
struct DataType< ::anymal_rsl_recording::StopRecordingResponse>
{
  static const char* value()
  {
    return DataType< ::anymal_rsl_recording::StopRecording >::value();
  }
  static const char* value(const ::anymal_rsl_recording::StopRecordingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ANYMAL_RSL_RECORDING_MESSAGE_STOPRECORDING_H
