// Generated by gencpp from file anymal_rsl_recording/StopRecordingInternal.msg
// DO NOT EDIT!


#ifndef ANYMAL_RSL_RECORDING_MESSAGE_STOPRECORDINGINTERNAL_H
#define ANYMAL_RSL_RECORDING_MESSAGE_STOPRECORDINGINTERNAL_H

#include <ros/service_traits.h>


#include <anymal_rsl_recording/StopRecordingInternalRequest.h>
#include <anymal_rsl_recording/StopRecordingInternalResponse.h>


namespace anymal_rsl_recording
{

struct StopRecordingInternal
{

typedef StopRecordingInternalRequest Request;
typedef StopRecordingInternalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StopRecordingInternal
} // namespace anymal_rsl_recording


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::anymal_rsl_recording::StopRecordingInternal > {
  static const char* value()
  {
    return "32fb2cde53384a7b9732fe4867a515c5";
  }

  static const char* value(const ::anymal_rsl_recording::StopRecordingInternal&) { return value(); }
};

template<>
struct DataType< ::anymal_rsl_recording::StopRecordingInternal > {
  static const char* value()
  {
    return "anymal_rsl_recording/StopRecordingInternal";
  }

  static const char* value(const ::anymal_rsl_recording::StopRecordingInternal&) { return value(); }
};


// service_traits::MD5Sum< ::anymal_rsl_recording::StopRecordingInternalRequest> should match
// service_traits::MD5Sum< ::anymal_rsl_recording::StopRecordingInternal >
template<>
struct MD5Sum< ::anymal_rsl_recording::StopRecordingInternalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::anymal_rsl_recording::StopRecordingInternal >::value();
  }
  static const char* value(const ::anymal_rsl_recording::StopRecordingInternalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::anymal_rsl_recording::StopRecordingInternalRequest> should match
// service_traits::DataType< ::anymal_rsl_recording::StopRecordingInternal >
template<>
struct DataType< ::anymal_rsl_recording::StopRecordingInternalRequest>
{
  static const char* value()
  {
    return DataType< ::anymal_rsl_recording::StopRecordingInternal >::value();
  }
  static const char* value(const ::anymal_rsl_recording::StopRecordingInternalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::anymal_rsl_recording::StopRecordingInternalResponse> should match
// service_traits::MD5Sum< ::anymal_rsl_recording::StopRecordingInternal >
template<>
struct MD5Sum< ::anymal_rsl_recording::StopRecordingInternalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::anymal_rsl_recording::StopRecordingInternal >::value();
  }
  static const char* value(const ::anymal_rsl_recording::StopRecordingInternalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::anymal_rsl_recording::StopRecordingInternalResponse> should match
// service_traits::DataType< ::anymal_rsl_recording::StopRecordingInternal >
template<>
struct DataType< ::anymal_rsl_recording::StopRecordingInternalResponse>
{
  static const char* value()
  {
    return DataType< ::anymal_rsl_recording::StopRecordingInternal >::value();
  }
  static const char* value(const ::anymal_rsl_recording::StopRecordingInternalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ANYMAL_RSL_RECORDING_MESSAGE_STOPRECORDINGINTERNAL_H
