// Generated by gencpp from file path_planner/ConcentrationWithHeader.msg
// DO NOT EDIT!


#ifndef PATH_PLANNER_MESSAGE_CONCENTRATIONWITHHEADER_H
#define PATH_PLANNER_MESSAGE_CONCENTRATIONWITHHEADER_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/PoseStamped.h>

namespace path_planner
{
template <class ContainerAllocator>
struct ConcentrationWithHeader_
{
  typedef ConcentrationWithHeader_<ContainerAllocator> Type;

  ConcentrationWithHeader_()
    : header()
    , concentration(0.0)
    , pose()  {
    }
  ConcentrationWithHeader_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , concentration(0.0)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _concentration_type;
  _concentration_type concentration;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::path_planner::ConcentrationWithHeader_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::path_planner::ConcentrationWithHeader_<ContainerAllocator> const> ConstPtr;

}; // struct ConcentrationWithHeader_

typedef ::path_planner::ConcentrationWithHeader_<std::allocator<void> > ConcentrationWithHeader;

typedef boost::shared_ptr< ::path_planner::ConcentrationWithHeader > ConcentrationWithHeaderPtr;
typedef boost::shared_ptr< ::path_planner::ConcentrationWithHeader const> ConcentrationWithHeaderConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::path_planner::ConcentrationWithHeader_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::path_planner::ConcentrationWithHeader_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::path_planner::ConcentrationWithHeader_<ContainerAllocator1> & lhs, const ::path_planner::ConcentrationWithHeader_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.concentration == rhs.concentration &&
    lhs.pose == rhs.pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::path_planner::ConcentrationWithHeader_<ContainerAllocator1> & lhs, const ::path_planner::ConcentrationWithHeader_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace path_planner

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::path_planner::ConcentrationWithHeader_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_planner::ConcentrationWithHeader_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::path_planner::ConcentrationWithHeader_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::path_planner::ConcentrationWithHeader_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_planner::ConcentrationWithHeader_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_planner::ConcentrationWithHeader_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::path_planner::ConcentrationWithHeader_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1afbe5b0dba4403221876028b40c67fa";
  }

  static const char* value(const ::path_planner::ConcentrationWithHeader_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1afbe5b0dba44032ULL;
  static const uint64_t static_value2 = 0x21876028b40c67faULL;
};

template<class ContainerAllocator>
struct DataType< ::path_planner::ConcentrationWithHeader_<ContainerAllocator> >
{
  static const char* value()
  {
    return "path_planner/ConcentrationWithHeader";
  }

  static const char* value(const ::path_planner::ConcentrationWithHeader_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::path_planner::ConcentrationWithHeader_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ConcentrationWithHeader.msg\n"
"std_msgs/Header header\n"
"float32 concentration\n"
"geometry_msgs/PoseStamped pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::path_planner::ConcentrationWithHeader_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::path_planner::ConcentrationWithHeader_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.concentration);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ConcentrationWithHeader_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::path_planner::ConcentrationWithHeader_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::path_planner::ConcentrationWithHeader_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "concentration: ";
    Printer<float>::stream(s, indent + "  ", v.concentration);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PATH_PLANNER_MESSAGE_CONCENTRATIONWITHHEADER_H
