(cl:defpackage anymal_rsl_recording-srv
  (:use )
  (:export
   "STARTRECORDING"
   "<STARTRECORDING-REQUEST>"
   "STARTRECORDING-REQUEST"
   "<STARTRECORDING-RESPONSE>"
   "STARTRECORDING-RESPONSE"
   "STARTRECORDINGINTERNAL"
   "<STARTRECORDINGINTERNAL-REQUEST>"
   "STARTRECORDINGINTERNAL-REQUEST"
   "<STARTRECORDINGINTERNAL-RESPONSE>"
   "STARTRECORDINGINTERNAL-RESPONSE"
   "STOPRECORDING"
   "<STOPRECORDING-REQUEST>"
   "STOPRECORDING-REQUEST"
   "<STOPRECORDING-RESPONSE>"
   "STOPRECORDING-RESPONSE"
   "STOPRECORDINGINTERNAL"
   "<STOPRECORDINGINTERNAL-REQUEST>"
   "STOPRECORDINGINTERNAL-REQUEST"
   "<STOPRECORDINGINTERNAL-RESPONSE>"
   "STOPRECORDINGINTERNAL-RESPONSE"
  ))

